var quotes = [
	"I was hoping, uh, by now that I would look older but that didn\'t happen.", 
	"I don\'t look older, I just look worse, I think.", 
	"Honestly, when I\'m walking down the street, no one\'s ever like, \"Hey, look at that man!\" I think they\'re just like \"Whoa! That tall child looks terrible!\"", "Get some rest, tall child! You can\'t keep burning the candle at both ends!", 
	"You ever seen on America\'s Most Wanted when they age a photo of someone? Just take my kindergarten photo and yellow the teeth and put bags under the eyes and be like \"This is what he would look like now\"", 
	"I was a very nervous kid, I was very anxious all the time when I was younger. But what\'s nice is that some of the things I was anxious about don\'t bother me at all anymore. ", 
	"Like, I always thought that quicksand was gonna be a much bigger problem than it turned out to be.", 
	"If you watch cartoons, quicksand is like the third biggest thing you have to worry about in adult life, behind real sticks of dynamite  and giant anvils falling on you from the sky.", 
	"I used to sit around and think about what to do about quicksand! I never thought about how to handle real problems in adult life. I was never like, \"Oh, what\'s it gonna be like when relatives ask to borrow money?\"", 
	"Now I\'ve gotten older, and not only have I never stepped in quicksand, I\'ve never even heard about it! No one\'s ever been like, \"Ey, if you\'re comin \' to visit, take I-90  \'cause I-95 has a little quicksand in the middle. Looks like regular sand, but then you\'re gonna start to sink into it.\"", 
	"A lot of guys my age I\'ll hear them say this, they\'ll go, \"Every day I think I\'m becoming more like my dad.\" I think I\'m becoming more like my mom? ", 
	"Because I Access Hollywood and one of the reporters said, \"Up next, we\'ve got an exclusive interview with Sandra Bullock\'s former husband Jessie James,\" and out loud, I went, \"Euch! This oughta be good!\" That\'s pure mom.",
	"But who cares? I didn\'t have, like, a job interview or anything.", 
	"Dad, I did not lie, I said that I brushed my teeth, I never specified that I brushed my teeth tonight! And if the court reporter reads back my remarks, you will see that I did not perjure myself.",
	"My mom was more like Nancy Grace. She would just make wild accusations all day long and wait for something to stick.", 
	"My mom would blame me for things that happened on the news. That is true.",
	"I woke up one morning when I was a kid and my mom was standing over my bed and said, \"I just heard that Princess Diana and her lover Dodi Al-Fayed have been killed in Paris.\" Like I had something to do with it! I was like, \"Mom, I have been here all night. You can feel the TV, it\'s warm.\" Luckily, I had a good alibi since I was in Wisconsin and 12.",
	"And in my head, when I was a little kid, I thought that Veronica was like 25, 30 years old. I was just talking to my mom the other week, I found out that when I was 10 Veronica was 13. So why was she in charge? All she could do was dial the telephone a little better than I could. 13 when I\'m 10? That\'s just like hiring a slightly bigger child. That would be like if you\'re going out of town for the week and you paid a horse to watch your dog.",
	"All right, here is the number where we\'ll be, and here\'s where we keep the dog food, and you\'re a horse.", 
	"Why do people do that? People always shush animals. They\'ll go, \"Hey, shh shh shh\" They\'ve never spoken.",
	"I remember in that movie, oh the kid in Home Alone 2. He gets into a stretch limousine on 5th avenue with a large cheese pizza and I thought, \"THIS IS THE HEIGHT OF LUXURY!!\"",
	"Lost in New York? The streets are numbered. How\'d you get lost in New York?",
	"I know it\'s kind of stupid to complain about a movie that came out 17 years ago, but I wasn\'t a comedian back then. So I have to do it now.", 
	"On the first day that he met me, the guy that is now my best friend, he met me the first day of kindergarten, he went home that night and said, \"Papa, today I met a boy with no eyes.\" And that was me.",
	"I remember when I was in junior high, we had this music appreciation class that we never appreciated.", 
	"13-year-olds are the meanest people in the world. They terrify me to this day.", 
	"If I\'m on the street on like a Friday at 3 PM I see a group of 8th graders on one side of the street I will cross to the other side of the street.",
	"8th graders will make fun of you, but in an accurate way. They will get to the thing that you don\'t like about you. They don\'t even need to look at you for long, they\'ll just be like, \"Hey, look at that high-waisted man! He got feminine hips!\" And I\'m like \"No!! That\'s the thing I\'m sensitive about!!!!\"", 
	"When I was a boy, I was also confused with a woman sometimes over the phone, because before I went through puberty, I had a voice like a little flute!", 
	"That\'s like when your gram would be like \"We\'d all go play jacks down at the soda fountain!\" and you\'re like, \"No one knows what you\'re talking about, you IDIOT.\" You know how you talk to your grandma?",
	"Now when people make fun of me, I deserve it.",
	"I know nothing about cars. I meant to learn about cars, and then I forgot.", 
	"Nothing that I know can help you with your car ever. Unless you\'re like, uh, \"Hey I\'ve got a flat tire, does anyone here know a lot about The Cosby Show?\" and then I could be like \"Oh, perhaps I could be of some assistance.\"",
	"I\'m one of the worst drivers I\'ve ever seen, and I just want you all to know that if you\'re ever on the highway behind me, uh, I hear you honking and I also don\'t want me to be doing what I\'m doing. I don\'t like that I\'m in that lane either, and I sure would like to get out of it!", 
	"I was on the highway in Texas recently which was like a highway filled with 13-year-olds. And I was in the far left lane and then it turned into a U-turn only lane and I started to make a U-turn but then I panicked because I didn\'t wanna make a U-turn! So I put the car in reverse and then merged right back onto the highway.",
	"The best thing about that was that after that, cars were pulling up and  looking over to see who just did that move, expecting to see like a 100-year-old blind dog who\'s texting while driving and drinking a smoothie, instead they see a 28-year-old healthy man trying his best.", 
	"It\'s wrong to make fun of people, you know, but it\'s so fun sometimes.", 
	"If you\'re comparing the badness of two words, and you won\'t even say one of them, that\'s the worse word.", 
	"What was a murder investigation like in 1935?? One cop would just walk in and be like, \"Detective! We found a pool of the killer\'s blood in that hallway!\" and he would just be like \"Hmmm, gross! Mop it up. Now then, back to my hunch.\"",
	"Look for clues. I\'ll tell you what we\'ll do! We\'ll draw chalk around the body is. That way, we\'ll know where it was.", 
	"Here\'s how easy it was to get away with bank robbery back in the 30\'s. As long as you weren\'t still there when the police arrived, you had a 99% chance of getting away with it. To the point that, like, those old bank robbers, they take credit for the bank robberies! Like, they come running out of there and they\'re like \"Ha ha ha! And if anyone asks, you tell em it was Golden Joe and the Suggins Gang!\" And then they like shoot  \'Suggins \' into the side of the wall. It\'s like, what, were bullets free back then? And they don\'t even disguise themselves.  They dress up for the bank robbery. They\'re rolling in there in, like, big suits and hats like they\'re going to church in Atlanta. They make a day of it!", 
	"It is so much easier not to do things than to do them, that you would do anything is totally remarkable.", 
	"Percentage-wise, it is 100% easier not to do things than to do them. So much fun not to do them!", 
	"In terms of, like, instant relief, cancelling plans is like heroin. It is an amazing feeling. Such instant joy.",
	"You ever ask an adult what they did over the weekend and they say they didn\'t do anything, their faces light up. ",
	"I have a friend named Megan, she\'s an elementary school teacher and I was out with her one night and she was drinking like a monster. And I said to her, \"Don\'t you have to do a shift at school tomorrow?\" And she went, \"Ahh, I\'ll just show a video.\" And I was like, \"That\'s why teachers show videos?\"", 
	"I like reading the New York Post because reading the New York Post is like talking to someone who heard the news, and now they\'re trying to give you the gist. It\'s like, you\'d get the same amount of information if you grabbed someone on the street and you were like, \"WHAT HAPPENED TODAY?\"",
	"The number one thing that you can be in the eyes of the New York Post is an angel. An angel is a child who has died. That is the best thing that you can be in the eyes of the New York Post. The less amount of time you live, the better in the eyes of the Post.",
	"A hero is any man who does his job. You\'ll a lot of times see headlines that are like, \"Hero Tutor Teaches After School,\" and you\'re like \"Yeah.\"", 
	"There are no children in the eyes of the New York Post. You\'re either a tot or you\'re dead and you\'re an angel.", 
	"No one has said \"bozo\" in 1,000 years.",
	"Went to a spa to get a massage, I went into the room to get the massage and the woman there told me to undress to my comfort level. So I put on a sweater and a pair of corduroy pants, and I felt safe.",
	"When I was 13 years old I stole 2 cigarettes from my older sister and I hid them in a shoebox under my bed with a copy of Cosmopolitan Magazine. And one day, my mom cleaned under my bed, and she found the shoebox. I came home from school and my mom was standing there holding it and she said, \"Hey mister! I found your treasure!\" And I never liked the way she phrased that, you know,  \'cause that made me sound like the world\'s lamest pirate.",
	"\"Oh, you\'re getting a chicken sandwich! Well that comes with a choice of either salad or fries.\" Those were the choices, salad or fries, the two most different foods in the universe. That\'s like saying, \"What kinda day do you wanna have? Do you wanna be active and go to the bathroom and stuff, or do you wanna lay on the floor moaning?\"", 
	"Oh, you\'re getting a chicken sandwich? Well with that, you can either go for a jog or smoke crack cocaine.", 
	"Oh, huh, well, if I get a plate of crack for the table, would you have some? You\'d have crack if I got a plate of crack? Yeah, okay, yeah we\'ll take an order of crack.", 
	"Sometimes when people order fries, they act like it\'s a little adventure.", 
	"They\'ll be like, \"Should we get a plate of fries for the table? Should we do it? Should we share some fries?\" They gotta make sure that everyone\'s onboard with it, it\'s like, \"If I get fries, you\'ll have a couple, right? If I get fries for the table, you\'ll have fries, should we do it? Yeah, let\'s be bad! C\'mon, let\'s do it, all right, we\'re gonna take a plate of fries!\" It\'s like a group of couples agreeing to do ecstasy together.", 
	"I would just come out of the recess yard and be like, \"Everyone get outta my way, I just wanna sit here and feed my birds.\"", 
	"I was in a restaurant near here in the West Village and I was at the urinal and an old man came in the bathroom with a walker like this  and he said this to me, he went, \"I\'m either having a drink or I have to pee, you\'re livin \' the golden years, kid, not me,\" like, he spoke in rhymes, it was crazy. It was such a weird interaction that I wasn\'t sure if it actually happened.", 
	"I have a girlfriend, and she\'s a female person.", 
	"I\'ve never been with my girlfriend and thought like, \"Oh, honey, tonight is going great, but do you know what would make it perfect? Charles and Ellen Mulaney. Come on! Let\'s get them in the mix. We\'ve been going pretty hot and heavy lately, I think it\'s time we bring in two older Catholic people.\"",
	"Before I had a girlfriend, I never had someone who\'s always standing next to me who can just point out obvious things that are happening.",
	"Like we\'ll be in a restaurant and my girlfriend will be like, \"you ordered your food an hour ago. It should be here by now\" and I\'m like \"yeahhh it should!\" It\'s like having a lawyer for everyday life.", 
	"Before I had a girlfriend, I had no standard of how I should be treated as a human being.", 
	"Like I\'ll book a ticket on some garbage airline. You know I don\'t want to name any actual airline so let\'s just make one up and so let\'s just call it Delta Airlines.", 
	"So I\'ve got my ticket at \"Delta Airlines\" and I show up at the airport. \"Can I get on the plane now please?\" And their like, \"NO! ITS BEEN DELAYED 9 HOURS!\" and I go \"Okayyy\" and I go to the bathroom. Then I come out of the bathroom and I go, \"any updates?\" and they go, \"yeah, we took off while you were in the bathroom. BECAUSE WE HATE YOU.  Now take this meal voucher that doesn\'t work, GO! FETCH!\" And I go, \"Okayyyyy\" and I go over to the Wolfgang Puck express and am like, \"Can I have a sandwich please?\" and they go, \"NOOOOOOOOO!\" and I go, \"Okayyyyyy\" And then I go over to the Delta help desk, which is an oxymoron and I go, \"Can I please go home on an airplane?\" and they go, \"Nooooo! In fact, we\'re gonna frame you for murder! And you\'re gonna go to jail for 30 years!\" and I go, \"Why are you doing this to me?\" and they go, \"Because we\'re Delta Airlines and life is a nightmare!\" But with my girlfriend she would be like, \"Let\'s see if Southwest has any flights?\" So it\'s better.",  
	"I\'ll just keep all my emotions right here and then one day, I\'ll die.", 
	"I used to drink and then I drank too much and I had to stop. That surprises a lot of audiences because I don\'t look like someone who used to do anything.",   
	"I look like I was just sitting in a room in a chair eating Saltines for like 28 years and then I walked right out here.",
	"Would you like, like an old turnip we found in the cabinet? Would that be good for you? Would you like that?",
	"I\'m really sorry about last night, it\'s just that I\'m mean and loud, it probably will happen again.", 
	"Here\'s a story I once heard about me. I guess I was 20 and I was at a party at someone\'s house and I had blacked out drinking, and someone came out of one of the rooms at this party holding like an old antique bottle with some liquid in it, and they said, \"Hey, is this whiskey or perfume?\" And apparently I grabbed it, drank all of it, and said, \"It\'s perfume.\" And it was.",
	"And Jake McNamara decided to throw a party at the teacher\'s house. Hooray! And everyone around town heard about it and we all got up individually and thought, \"Okay, let\'s go over there and destroy the place.\"",
	"I walked into this party. Everyone I had even met was at this party, and everyone was drinking like it was the end of the world. People were drinking like it was the civil war and a doctor was coming to saw our legs off.",  
	"It was totally unsupervised; we were like dogs without horses. We were running wild.",
	"My friend John, who is now a father, this man now has a baby, he grabbed a 40, smashed it on the ground and yelled, \"SCATTER!!\"",
	"We all ran in different directions, I ran into the laundry room and I jumped up on the washing machine and I crawled out through a window into the backyard and now I\'m running through the backyard and there was this big chain link fence and I thought I\'ve never climbed a fence that high before. And then I woke up at home.",
	"I am often wrong.", 
	"I\'ll take your advice, friend I\'ve never listened to before.",  
	"I\'ll just be like hey, sometimes I pee a lot and the doctor would be like, \"Me too, crazy right?!?\" And I\'ll be like, \"I get nervous on airplanes.\"",   
	"All of his jokes were anti work, which is not always what you want from a health care professional.",  
	"You ever have those days where you\'re like, \"This might as well happen. Adult life is already so weird.\"",  
	"It was as if a ghost had been trapped in my belly and finally flew out towards the light.", 
	"\"Batman look, I\'m one of those people who, when you take blood from me, sometimes I can faint. And I was in the waiting area for 3 hours and I haven\'t eaten anything all day and I\'m really worried I\'m gonna faint.\" And Batman said to me, and I'll never forget it, \"Pshh, you\'re not gonna faint!\" So, I stick my arm out, Batman puts the needle in my arm, and I\'m immediately on the ground.",   
	"I went to that clinic 2 years later for a different checkup and as I was leaving, who do I run into but Batman. And he smiled at me and he was wearing reading glasses to show that time had passed.",
	"I love to play venues where if the guy that built the venue could see me on the stage, he would be a little bit bummed about it.",
	"What a historic and beautiful and deeply haunted building this is. I keep walking through cold spots being like, \'I wonder who that used to be.\'",
	"I asked my mom if she\'d ever seen a ghost. That's where we\'re at conversation-wise in our relationship as a mother and son, because I\'m 35 and I don't have any children to talk about and she doesn\'t understand my career.",
	"So I was home for Christmas and we were just eating Triscuits in silence and I was staring at the floor and I was like, Well, here goes nothing. \'You ever seen a ghost?\' And my mom said, \'Yes.'\ Which is the best answer.",
	"And then my dad said, \'Let\'s change the subject!\' And I think he was just doing that dad-thing of, like, \'This is a weird topic and I want to talk about a book I read about World War II.\'",
	"None of us really know our fathers. Anyway... My dad is so weird. I\'d love to meet him someday.",
	"My dad is a lawyer and he was a debate team champion. So he would pick us apart psychologically.",
	"I was like 12 years old and my dad walked up to me and he said, \'Hello... Hello, I\'m Chip Mulaney. I\'m your father.\'",
	"You\'re here. That\'s great. You all showed up. I appreciate it. And then we showed up so you got to see the things that you paid to see. That\'s great. You don\'t always get to see the things that you paid to see.",
	"I love doing stand-up for crowds because this right here, this reminds me of assembly in grade school. And assembly was the only part of school I ever liked. Once you leave school, you don\'t get to have assembly. This is the closest we get in adult life to assembly.",
	"Cause look at you all, you\'re just sitting there in chairs, looking at a guy with absolutely no expertise, who\'s going to talk for a while. Although this is different than assembly because you bought tickets, you knew this was coming. Assembly you never knew was coming when you were a kid.",
	"You get to the gym and the whole school is sitting on the floor. You\'re like, \'What are we, about to graduate from Tuesday?\'",
	"My principal would always come out to kick things off. She\'d be like, \'Children, rather than continue to teach you how to read, we have cleared the entire day for this random guy.\'",
	"I was once in assembly listening to a guy talk about smoking crack. My social studies teacher yelled at me, \'Sit up straight! Show some respect.\' I was like, \'He\'s smoking cocaine.\' Sit up straight? He\'s standing on a 45-degree angle. Or, as junkies call it, first position.",
	"We had the same Stranger Danger speaker every year when I was a kid, his name was Detective JJ Bittenbinder.",
	"His name is ridiculous. That was his name. It was JJ Bittenbinder.",
	"So try being seven years old and you\'re sitting five feet away from him. He\'s still got blood on his shoes. And he\'s looking at you in the eye to tell you for the first time in your very young life that some adults find you incredibly attractive. And they may just have to kill you over it. Okay, c\'est la vie, go be kids, go have fun.",
	"By the way, Detective JJ Bittenbinder wore three-piece suits. He also wore a pocket watch. Two years in a row, he wore a cowboy hat. He also had a huge handlebar mustache.",
	"None of that matters, but it's important to me that you know that. He did not look like his job description. He looked like he should be the conductor on a locomotive powered by confetti. But, instead, he made his living in murder. He was the weirdest person I ever saw in my entire life.",
	"He was a man most acquainted with misery. He could look at a child and guess the price of their coffin.",
	"So Bittenbinder came every year with a program to teach us about the violent world waiting for us outside the school gym, and that program was called Street Smarts!",
	"Time for Street Smarts with Detective JJ Bittenbinder. Shut up! You\'re all gonna die. Street Smarts!",
	"Okay, tip number one. Street Smarts! Let\'s say a guy pulls a knife on you to mug you.",
	"You know how a mugger thinks. \'Man, I need cash for drugs right now. Hey, maybe that eight-year-old with the Aladdin wallet that only has blank photo laminate pages in it will be able to help.",
	"You put a $50 bill in the money clip then when a guy flashes a blade, you go, \'You want my money, go get it!\' Then you run the other direction.",
	"You go home to your parents. \'Hey, Dad. Can I have a silver money clip with a $50 bill in it, please? Don\'t worry. I\'m only going to chuck it into the gutter and run away at the first sign of trouble. The man with the mustache told me to do it.\'",
	"\'Tip number three. Street Smarts! You kids have no upper body strength.\' And we were like, \'We know but, hey.\'",
	"He\'s not gonna know how to fight back with two little sneakers coming at him.",
	"If the Lindbergh baby had steel-toe boots, he\'d still be alive today. Street Smarts!",
	"Yeah, he was not a \'spoonful of sugar helps the medicine go down\' kind of guy. He was more like, \'Brush your teeth. Now, boom, orange juice. That's life.\'",
	"Bittenbinder, he didn\'t want us to not get kidnapped. He wanted us to almost get kidnapped and then fight the guy off using weird, psych-out, back-room Chicago violence.",
	"When I saw the perp approachin\', I chewed up a tab of Alka-Seltzer I carry with me at all times. This created a foaming-at-the-mouth appearance that made it look like I had rabies. Now I\'ve thrown him off his rhythm.",
	"Bittenbinder told me things that haunt me to this day. He came one year for assembly. He goes, \'Okay, when you get kidnapped...\' Not if, when.",
	"I\'ll be at a wedding reception and someone\'ll be like, \'You coming to the hotel bar after? We\'re all gonna get drinks and keep the party going.\' I\'m like, \'Nah, sister. You\'re not getting me to no secondary location. You want it? Go get it!\' Street Smarts! Stay alert out there.",
	"I just got a letter from my college, which was fun \'cause mail, you know? So I open up the letter and they said, \'Hey, John, it\'s college. You remember?\' I say, \'Yes, of course.\' And they said... How did they phrase it? They said, \'Give us some money!\'",
	"What kind of a cokehead relative is my college? You spent it already? I gave you more money than the Civil War cost and you spent it already?",
	"I have friends I went to college with and they\'re like, \'You should donate and be a good alumnus.\' And they wear shirts that say \"school\" and it\'s like, look... if you\'re an adult still giving money to your college, college is a $120,000 hooker and you are an idiot who fell in love with her. She\'s not going to do anything else for you. It\'s done.",
	"In their letter they were like, \'Hey, it\'s been a while since you\'ve given us money.\' I was like, \'Hey, it\'s been a while since you\'ve housed and taught me.\'",
	"I went to college, I was 18 years old, I looked like I was 11. I lived like a goddamn Ninja Turtle.",
	"I didn\'t drink water the entire time. I lived on cigarettes and alcohol and Adderall.",
	"College was like a four-year game show called Do My Friends Hate Me or Do I Just Need to Go to Sleep?",
	"But instead of winning money, you lose $120,000. By the way, I agreed to give them $120,000 when I was 17 years old. With no attorney present. That\'s illegal. They tricked me.",
	"Two guys in clip-on ties are like, \'Come on, son, do the right thing. Sign here and be an English major.\' And I was like, \'Okay.\' Yes, you heard me, an English major. I paid $120,000. How dare you clap? How dare you clap for the worst financial decision I ever made in my life? I paid $120,000 for someone to tell me to go read Jane Austen and then I didn\'t.",
	"I know you\'d be disappointed when you open up the duffel bag and you realize it\'s not real cocaine, it\'s like powdered baby aspirin or whatever they do. But at least you have baby aspirin.",
	"We made these big piles of clothes, we put the piles into these big boxes, then we put the boxes into the back of my car, and then they stayed there for four months.",
	"And then one day my wife said, \'Hey, you took that stuff to Goodwill, right?\' And I said, \'Of course I did! On an unrelated note, I'm going to walk out the front door right now.\'",
	"So then I had to speed to Goodwill really fast. It was charitable, but it was also fast and violent, because I was throwing boxes at people.",
	"The boxes were so heavy I couldn\'t even say what was in them. I was like, \'This one\'s shirts. I got a bunch of shirts! Take\'em away!\' The guy tried to give me a big receipt. He\'s like, \'Take this receipt for the clothing for your taxes.\' How do I write that on my taxes?",
	"Dear IRS, please deduct from my federal income tax one XXL Billabong T-shirt from youth. It was too big. My mom said it could be a sleep shirt. Please deduct this from my 2017 income.",
	"\'Well, if it\'s too big you can just wear it as a sleep shirt.\' No, I get that, Mom, but why don\'t we just tell our relatives that I\'m a four-year-old boy and I don\'t wear a man\'s XXL T-shirt? \'Because we don\'t say that when someone gives us a gift because that would not be polite.\' Oh, I get it.",
	"So rather than violate these meaningless politeness rules, I\'ll just go to bed in a smock like goddamn Ebenezer Scrooge. Why don\'t you give me a candle for looking in the mirror and a floppy hat and I\'ll tremble off to bed in my long Victorian nightgown? Was there ever even a ghost, Mother, or was the dead Victorian girl you saw just me all along?",
	"Of all the sentences in that email I would be ashamed to have read out loud in a court of law, I think the top one is\'See you at improv practice.\'",
	"Strange, the passage of time. I\'m not that old. I\'m 35, that is not old. But I am in a new phase right before old called\'gross.\'",
	"I never knew about this, but I am now gross. I am damp all the time. I am damp now and I will be damp later. Like the back of a dolphin, my back. I am slick.",
	"I\'m gross. I have hair on my shoulders now. I don\'t even have a joke for that.",
	"I\'m 35, but I\'m still like, \'Hey, when am I going to get big and strong?\'",
	"I\'m like an iPhone, it\'s going to be worse versions of this every year, plus I get super hot in the middle of the afternoon for no reason.",
	"As I get older, it\'s tough to not get grumpy. It\'s tempting. I get grumpy about some things. Like, I can\'t listen to any new songs because every new song is about how tonight is the night and how we only have tonight. That is such 19-year-old garbage. I want to write songs for people in their 30s called \'Tonight\'s No Good, How About Wednesday? Oh, You\'re in Dallas on Wednesday? Okay. Well, Let\'s Just Not See Each Other for Eight Months And It Doesn\'t Matter at All.\'",
	"I\'m trying to stay nice though, because when I was a kid, I was raised that you should be nice to everyone in every situation because you never know their story. But now, at the end of my life, I don\'t know, because a lot of people don\'t seem that nice and they seem to be doing fine in the world.",
	"The host was Sir Patrick Stewart, the great Sir Patrick Stewart, and this is how he introduced the musical guest. \'Ladies and gentlemen, Salt-N-Pepa!\' Like he was surprised by Pepa.",
	"Like minutes before they\'d been, \'Sir Patrick, we can\'t find Pepa anywhere.\' And he\'s like, \'If we must go on with Salt alone, we will go on with Salt alone!\' And they were like, \'Three, two, one,\' and Pepa burst through the door and he\'s like, \'Ladies and gentlemen, Salt and... what\'s this? Pepa!\'",
	"And they would all come in to Saturday Night Live and they'd have to meet with me because I was a little rat writer and they\'d have to talk about the sketches. They\'d sit on my office couch that had like bed bugs and stuff. It was great. Like, they were famous, but it was my couch.",
	"He\'s Mick Jagger. That\'s his name. He\'s played to stadiums of 20,000 people cheering for him like he\'s a god for 50 years. That must change you as a person. If you do that for 50 years, you\'re never again going to be like, \'Um, does anyone have a laptop charger I could borrow?\'",
	"\'Hi. Knock, knock. Sorry.\' That\'s how I walk into rooms. I am 35 years old, I am six feet tall. I lower myself, I go, \"Hi. Knock, knock.\" I say\'knock, knock\' out loud.",
	"Mick Jagger would go like this, \'Diet Coke!\' And one would appear in his hand.",
	"But if all of us could go, \'Diet Coke!\' and one would appear in our hand, we\'d do it all day long. Even if you don\'t like Diet Coke, you\'d just summon\'em so you could chuck\'em at oncoming cars.",
	"Fifty years ago, if you were on the telephone with your friend and suddenly the line just went dead, that meant your friend was murdered.",
	"Back in the 1940s, the phone was like a wood box... with a thing on it. I don\'t know. It had its own room. You\'d go, \'That's the phone's room!\' And it was expensive.",
	"And then you\'d take the cup on the string or whatever... There weren\'t even numbers. You\'d just go, \'Hello? Anyone? Anyone in the world?\' Then you\'d go, \'Operator, ring me Neptune 5-117.\' And the operator was a real person that you had to be nice to. She\'d be like, \'One moment, please. I\'m putting wires into a board filled with holes to move the voices around, \'cause it is the \'40s.\'",
	"Everything was slower back in the old days\'cause they didn\'t have enough to do, so they had to slow things down to fill the time.",
	"I don\'t know if you read history, but back then people would wake up and go, \'God, it\'s the old times. I gotta wear all those layers. There\'s no Zyrtec or nothing. Okay, we gotta... We gotta think of some weird slow activities to fill the day.\' And they did. Have you ever seen old film from the past of people just waving at a ship? What if I called you now to do that? Hey, what are you doing Monday at 10:00 a.m.? All right, there\'s a Norwegian Cruise Line leaving for Martinique. Here\'s my plan, you and me get very dressed up, including hats, and then we wave handkerchiefs at it until it disappears over the horizon. No, I don\'t know anyone on the ship.",
	"The world is run by computers, the world is run by robots and we spend most of our day telling them that we\'re not a robot just to log on and look at our own stuff. All day long. May I see my stuff, please? \'I smell a robot. Prove, prove, prove. Prove to me you\'re not a robot. Look at these curvy letters. Much curvier than most letters, wouldn\'t you say? No robot could ever read these. You look, mortal, if ye be. You look and then you type what you think you see. Is it an \'E\' or is it a \'3\'? That\'s up to ye. The passwords of past you've correctly guessed, but now it\'s time for the robot test! I\'ve devised a question no robot could ever answer. Which of these pictures does not have a stop sign in it?\'",
	"You spend most of your day telling a robot that you\'re not a robot. Think about that for two minutes and tell me you don\'t want to walk into the ocean.",
	"I just like old-fashioned things. I was in Connecticut recently, doing white people stuff.",
	"That is in the middle of the Civil War. And the whole town built a gazebo.",
	"What was that town meeting like? \'All right, everyone, first order of business, we have all the telegrams from Gettysburg with the war dead. Let\'s see here. Okay, everyone\'s husband and brother and... everyone died. Okay. Josiah, you had something?\' \'Yes, I do. How\'d you like to be indoors and out of doors all at once? Ever walk into the park with your betrothed and it starts to rain, but you still want to hold hands? Well, may I introduce you to, and my condolences again to everyone, the gazebo!\'",
	"Building a gazebo during the Civil War, that\'d be like doing stand-up comedy now.",
	"And neither do any of you, and neither do your parents, because there\'s a horse loose in the hospital. It\'s never happened before, no one knows what the horse is going to do next, least of all the horse. He\'s never been in a hospital before, he\'s as confused as you are.",
	"They try to find experts on the news. They\'re like, \'We\'re joined now by a man that once saw a bird in the airport.\'",
	"When a horse is loose in a hospital, you got to stay updated. So all day long you walk around, \'What\'d the horse do?\' The updates, they\'re not always bad. Sometimes they\'re just odd. It\'ll be like, \'The horse used the elevator?\' I didn\'t know he knew how to do that.",
	"Those are those quiet days when people are like, \'It looks like the horse has finally calmed down.\' And then ten seconds later the horse is like, \'I'm gonna run towards the baby incubators and smash \'em with my hooves. I\'ve got nice hooves and a long tail, I\'m a horse!\'",
	"Then you go to brunch with people and they\'re like, \'There shouldn\'t be a horse in the hospital.\' And it\'s like, \'We\'re well past that.\'",
	"And then, for a second, we were like, \'Maybe the horse-catcher will catch the horse.\' And then the horse is like, \'I have fired the horse-catcher.\'",
	"He can do that? That shouldn\'t be allowed no matter who the horse is. I don\'t remember that in Hamilton.",
	"I used to pay less attention before it was a horse. Also, I thought the last guy was pretty smart, and he seemed good at his job, and I\'m lazy by nature. I\'m lazy by nature too.",
	"When I walk down the street, I need everybody, all day long, to like me so much. It\'s exhausting. My wife said that walking around with me is like walking around with someone who\'s running for mayor of nothing.",
	"My wife and I went to Best Buy to get a TV. We didn\'t end up getting the TV. I was afraid that the Best Buy guy was going to be mad at me, so I bought an HDMI cable.",
	"I hand the guy the HDMI cable. He takes it, he scans it, he says, \'Do you have a Best Buy Rewards card?\' And I said, \'No, I wish!\'",
	"Fourteen years ago, I smoked cocaine the night before my college graduation. Now I\'m afraid to get a flu shot. People change.",
	"Petunia likes to be very social but she can\'t walk very far because she has a flat face, so she can\'t breathe by design.",
	"My wife and I walk around New York City pushing Petunia the French bulldog in a stroller, and it\'s a big stroller and it has a big black hood. And people lean in to see the baby.",
	"Do you think that in da Vinci\'s The Last Supper that Jesus of Nazareth is sitting in front of a turkey?",
	"And I experienced both the compliment and the insult in real time. He was like, \'Hey cool guy.\' I was like, \'Hey.\' She was like, \'That's mean.\' Was like, \'Right.\'",
	"I personally take the subway a lot in New York. I love the subway, because of the male and female voices that narrate the subway. That man and that woman. The woman who does the subway announcements and her way too loud husband.",
	"Your server Michael will be right over. Oh, by the way, killing a waiter in the state of New York is a class 8 felony. I\'m going to get you some bread.",
	"It\'s like there\'s a DJ in the back of the patrol car. It sounds like two sirens talking to each other."
	
]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
